### ISSUE TITLE
Légende statuts conservation

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/GeoNature-BiodivTerritoires#15]
Prévoir d'ajouter une légende des statuts de conservation

**Comment by lpofredc** [comment]
Revue de la modal des statuts de conservation:
![Screenshot_2021-04-08 La biodiversité de Aubenas (Communes 07019) Biodiv'Territoires](https://user-images.githubusercontent.com/22891423/114031828-090ac700-987c-11eb-8066-f4db93309352.png)
